version: '3'
services:
  redis:
    image: redis:3.2-alpine
    # command: redis-server --appendonly yes --requirepass cnode
    volumes:
      - egg-redis:/data
    networks:
      - cnode
    ports:
      - 6379:6379

  mongo:
    image: mongo:4.0.3
    restart: always
    environment:      
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=cnode
    volumes:
      - egg-mongo:/data/db
      - ./init.d/mongo/:/docker-entrypoint-initdb.d/
    networks:
      - cnode
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
    networks:
      - cnode
    depends_on:
      - mongo
    ports:
      - 8081:8081

volumes:
  egg-mongo:
  egg-redis:

networks:
  cnode:
    driver: bridge    
